### ADD A Post:
POST http://localhost:8080/api/v1/posts
Authorization: bearer {{adminJWT}}
Content-Type: application/json

{
  "title": "Spring Boot Lec 18",
  "description": "The Basics of DI",
  "content": "Annotations in spring boot"
}

### ADD A Post:
POST http://localhost:8080/api/v1/posts
Authorization: bearer {{adminJWT}}
Content-Type: application/json

{
  "title": "Spring Boot Lec 2",
  "description": "The Basics of DI",
  "content": "Annotations in spring boot"
}

### ADD A Post:
POST http://localhost:8080/api/v1/posts
Authorization: bearer {{adminJWT}}
Content-Type: application/json

{
  "title": "Spring Boot Lec 3",
  "description": "The Basics of DI",
  "content": "Annotations in spring boot"
}

### ADD A Post:
POST http://localhost:8080/api/v1/posts
Authorization: bearer {{adminJWT}}
Content-Type: application/json

{
  "title": "",
  "description": "",
  "content": ""
}

### ADD A Post:
POST http://localhost:8080/api/v1/posts
Authorization: bearer {{adminJWT}}
Content-Type: application/json

{
  "title": "Spring Boot Lec 5",
  "description": "The Basics of DI",
  "content": "Annotations in spring boot"
}

### GET ALL Posts:
GET http://localhost:8080/api/v1/posts
Authorization: bearer {{userJWT}}

### GET ALL Posts pagination:
GET http://localhost:8080/api/v1/posts?pageNo=0&pageSize=-1&sortDir=asc
Authorization: bearer {{adminJWT}}

### GET ALL Posts pagination:
GET http://localhost:8080/api/v1/posts?pageNo=1&pageSize=2&sortDir=asc
Authorization: bearer {{userJWT}}

### GET ALL Posts pagination:
GET http://localhost:8080/api/v1/posts?pageNo=0&pageSize=2&sortDir=asc&sortBy=title,id
Authorization: bearer {{userJWT}}

### GET A Post by id:
GET http://localhost:8080/api/v1/posts/1
Authorization: bearer {{userJWT}}

### PUT A POST
PUT http://localhost:8080/api/v1/posts/1
Authorization: bearer {{adminJWT}}
Content-Type: application/json

{
  "title": "Spring Boot Lec 1!!!",
  "description": "The Basics of DI!!",
  "content": "Annotations in spring boot!"
}

### Delete a post by id:
DELETE http://localhost:8080/api/v1/posts/1
Authorization: bearer {{adminJWT}}


### add a comment:
POST http://localhost:8080/api/v1/posts/1/comments
Content-Type: application/json
Authorization: bearer {{userJWT}}

{
  "comment": "Nice Read"
}


### GET comments by post id
GET http://localhost:8080/api/v1/posts/1/comments
Authorization: bearer {{userJWT}}Ï

### UPDATE Comment By ID:
PUT http://localhost:8080/api/v1/comments/1
Authorization: bearer {{userJWT}}
Content-Type: application/json

{
  "comment": "Nice Read!!!"
}

### Delete a comment:
DELETE http://localhost:8080/api/v1/comments/1
Authorization: bearer {{adminJWT}}


### Demo Authenticated user details:
GET http://localhost:8080/api/v1/auth/me
Authorization: bearer {{userJWT}}


###register a user:
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "username": "moe",
  "email": "moshiko@gmail.com",
  "password": "Passw0rd1!"
}


###login as admin:
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "Passw0rd1!"
}


###login as user:
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "user",
  "password": "Passw0rd1!"
}
