### ADD A Post:
POST http://localhost:8080/api/v1/posts
Authorization: Basic admin Passw0rd1!
Content-Type: application/json

{
  "title": "Spring Boot Lec 6",
  "description": "The Basics of DI",
  "content": "Annotations in spring boot"
}

### ADD A Post:
POST http://localhost:8080/api/v1/posts
Authorization: Basic admin Passw0rd1!
Content-Type: application/json

{
  "title": "Spring Boot Lec 2",
  "description": "The Basics of DI",
  "content": "Annotations in spring boot"
}

### ADD A Post:
POST http://localhost:8080/api/v1/posts
Authorization: Basic admin Passw0rd1!
Content-Type: application/json

{
  "title": "Spring Boot Lec 3",
  "description": "The Basics of DI",
  "content": "Annotations in spring boot"
}

### ADD A Post:
POST http://localhost:8080/api/v1/posts
Authorization: Basic admin Passw0rd1!
Content-Type: application/json

{
  "title": "Spring Boot Lec 4",
  "description": "The Basics of DI",
  "content": "Annotations in spring boot"
}

### ADD A Post:
POST http://localhost:8080/api/v1/posts
Authorization: Basic admin Passw0rd1!
Content-Type: application/json

{
  "title": "Spring Boot Lec 5",
  "description": "The Basics of DI",
  "content": "Annotations in spring boot"
}

### GET ALL Posts:
GET http://localhost:8080/api/v1/posts
Authorization: Basic user Passw0rd1!

### GET ALL Posts pagination:
GET http://localhost:8080/api/v1/posts?pageNo=0&pageSize=2&sortDir=asc

### GET ALL Posts pagination:
GET http://localhost:8080/api/v1/posts?pageNo=1&pageSize=2&sortDir=asc

### GET ALL Posts pagination:
GET http://localhost:8080/api/v1/posts?pageNo=0&pageSize=2&sortDir=asc&sortBy=title,id

### GET A Post by id:
GET http://localhost:8080/api/v1/posts/1

### PUT A POST
PUT http://localhost:8080/api/v1/posts/1
Authorization: Basic admin Passw0rd1!
Content-Type: application/json

{
  "title": "Spring Boot Lec 1!!!",
  "description": "The Basics of DI!!",
  "content": "Annotations in spring boot!"
}

### Delete a post by id:
DELETE http://localhost:8080/api/v1/posts/1
Authorization: Basic admin Passw0rd1!


### add a comment:
POST http://localhost:8080/api/v1/posts/1/comments
Content-Type: application/json
Authorization: Basic user Passw0rd1!

{
  "comment": "Nice Read"
}


### GET comments by post id
GET http://localhost:8080/api/v1/posts/1/comments
Authorization: Basic user Passw0rd1!

### UPDATE Comment By ID:
PUT http://localhost:8080/api/v1/comments/1
Authorization: Basic user Passw0rd1!
Content-Type: application/json

{
  "comment": "Nice Read!!!"
}

### Delete a comment:
DELETE http://localhost:8080/api/v1/comments/1
Authorization: Basic admin Passw0rd1!


### Demo Authenticated user details:
GET http://localhost:8080/api/v1/auth/me
Authorization: Basic user Passw0rd1!

###register a user:
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "username": "avi",
  "email": "avi@gmail.com",
  "password": "Passw0rd1!"
}


###artist->albums->songs